routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/', 'HomeController@index');

Auth::routes([
    'register'  => false,
    'reset'     => false,
    'verify'    => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'admin', 'prevent-back-history'])->group(function () {
    Route::get('admin-dashboard', 'AdminDashboardController@index')->name('admin-dashboard');
    Route::resource('users', 'UserController');
    Route::resource('clients', 'AdminClientController');
    Route::post('admin-clients-search', 'AdminClientController@adminClientsSearch')->name('admin-clients-search');
    Route::get('clients-import', 'AdminClientController@clientImport')->name('clients.import');
    Route::post('clients-import', 'AdminClientController@clientImportSave')->name('clients.import');
    Route::post('client_payment', 'AdminClientController@clientPayment')->name('client-payment');
    Route::get('invoice_print/{id}', 'AdminClientController@invoicePrint')->name('invoice-print');
    Route::get('invoice_download/{id}', 'AdminClientController@invoicePdf')->name('invoice-download');
    Route::post('document_upload', 'AdminClientController@documentUpload')->name('document-upload');
    Route::resource('embassy-approve', 'AdminEmbassyApproveController');
    Route::post('embassy-approve-list', 'AdminEmbassyApproveController@embassyApproveList')->name('embassy-approve-list');
    Route::get('embassy-approve-import', 'AdminEmbassyApproveController@embassyApproveImport')->name('embassy-approve-import');
    Route::post('embassy-approve-import', 'AdminEmbassyApproveController@embassyApproveSave')->name('embassy-approve-import');
    Route::resource('medical-status', 'AdminMedicalStatus');
    Route::resource('malaysia-clients', 'MalaysiaClientController');
    Route::resource('hiaring-moods', 'AdminHiaringMoodController');
    Route::resource('companies', 'AdminCompanyController');
});

Route::middleware(['auth', 'editor', 'prevent-back-history'])->group(function () {
    Route::get('editor-dashboard', 'EditorDashboardController@index')->name('editor-dashboard');
    Route::resource('editor-clients', 'EditorClientController');
    Route::post('editor-clients-search', 'EditorClientController@editorClientsSearch')->name('editor-clients-search');
    Route::post('editor_client_payment', 'EditorClientController@clientPayment')->name('editor-client-payment');
    Route::get('editor_invoice_print/{id}', 'EditorClientController@invoicePrint')->name('editor-invoice-print');
    Route::get('editor_invoice_download/{id}', 'EditorClientController@invoicePdf')->name('editor-invoice-download');
    Route::post('editor_document_upload', 'EditorClientController@documentUpload')->name('editor-document-upload');
});

Route::middleware(['auth', 'viewer', 'prevent-back-history'])->group(function () {
    Route::get('viewer-dashboard', 'ViewerDashboardController@index')->name('viewer-dashboard');
});

Route::get('migrate/{key}', function ($key) {
    if ($key == 'Rejohn@1234') {
        try {
            \Artisan::call('migrate');
            echo 'Migrated Successfully!';
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    } else {
        echo 'Not matched!';
    }
});


Route::get('clear', function () {
    \Artisan::call('optimize:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    \Artisan::call('config:clear');
    echo "Run clear Successfully";
});

app/Models/HiaringMood.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HiaringMood extends Model
{
    protected $guarded = [];
}

resources/views/admin/hiaring_mood/create.blade.php
@extends('layouts.layout')

@if(isset($hiaringMood))
@section('title', 'Hiaring Mood Update')
@else
@section('title', 'Hiaring Mood Create')
@endif

@section('content')

@component('partials.breadcrumb',[
'title' => isset($hiaringMood) ? 'Hiaring Mood Update' : 'Hiaring Mood Create',
'activePage' => isset($hiaringMood) ? 'Hiaring Mood Update' : 'Hiaring Mood Create'
])
@endcomponent

<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">@if(isset($hiaringMood)) Update Hiaring Mood @else Create Hiaring Mood @endif</h3>
        </div>
        <form action="{{ isset($hiaringMood) ? route('hiaring-moods.update', $hiaringMood->id) : route('hiaring-moods.store') }}" method="POST">
            @csrf
            @if(isset($hiaringMood))
            @method('PUT')
            @endif
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group @error('name') has-error @enderror">
                            <label for="firstName" class="control-label">Hiaring Mood Name <span class="text-danger">*</span></label>
                            <input type="text" name="name" class="form-control" id="hiaringMood" value="{{ isset($hiaringMood) ? $hiaringMood->name : old('name') }}" placeholder="Enter Hiaring Mood Name" required>
                            @error('name')
                            <span class="help-block text-danger">{{ $message }}</span>
                            @enderror
                            @error('slug')
                            <span class="help-block text-danger" style="color: red !important;">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="{{ route('hiaring-moods.index') }}" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-info pull-right">@if(isset($hiaringMood)) Update Hiaring Mood @else Create Hiaring Mood @endif</button>
            </div>
        </form>
    </div>
</section>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('vendors/sweet-alert/sweetalert.css') }}">
@endsection

@section('scripts')
<script src="{{ asset('vendors/sweet-alert/sweetalert.js') }}"></script>

@if(session('error'))
<script>
    $(document).ready(function() {
        Swal.fire({
            title: "Alert",
            text: "{{ session('error') }}",
            icon: "error",
            showCancelButton: true,
            confirmButtonText: 'Exit',
            cancelButtonText: 'Stay on the page'
        });
    });
</script>
@endif
@endsection

resources/views/admin/hiaring_mood/index.blade.php
@extends('layouts.layout')

@section('title', 'Hiaring Mood')

@section('content')

@component('partials.breadcrumb',[
'title' => 'Hiaring Mood List',
'activePage' => 'Hiaring Mood List'
])
@endcomponent

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-users"></i>
                    <h3 class="box-title">Hiaring Mood</h3>
                    <div class="box-tools">
                        <a href="{{ route('hiaring-moods.create') }}" type="button" class="btn btn-info btn-flat btn-xs pull-right">Add Hiaring Mood</a>
                    </div>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                            @forelse ($hmoods as $data)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $data->name }}</td>
                                <td>
                                    <a href="{{ route('hiaring-moods.edit', $data->id) }}" type="button" class="btn btn-info" data-toggle="tooltip" data-placement="top" title="Edit {{ $data->name }} info"><i class="fa fa-edit"></i></a>
                                    {{-- <a href="#" type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Delete {{ $data->name }}"><i class="fa fa-trash"></i></a> --}}
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="3" class="text-center">No Hiaring Mood.</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('vendors/sweet-alert/sweetalert.css') }}">
@endsection

@section('scripts')
<script src="{{ asset('vendors/sweet-alert/sweetalert.js') }}"></script>
@if(session('success'))
<script>
    $(document).ready(function() {
        Swal.fire(
            'Good job!',
            "{{ session('success') }}",
            'success'
        );
    })
</script>
@endif

@if(session('error'))
<script>
    $(document).ready(function() {
        Swal.fire({
            title: "Alert",
            text: "{{ session('error') }}",
            icon: "error",
            showCancelButton: true,
            confirmButtonText: 'Exit',
            cancelButtonText: 'Stay on the page'
        });
    });
</script>
@endif
@endsection