routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/', 'HomeController@index');

Auth::routes([
    'register'  => false,
    'reset'     => false,
    'verify'    => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'admin', 'prevent-back-history'])->group(function () {
    Route::get('admin-dashboard', 'AdminDashboardController@index')->name('admin-dashboard');
    Route::resource('users', 'UserController');
    Route::resource('clients', 'AdminClientController');
    Route::post('admin-clients-search', 'AdminClientController@adminClientsSearch')->name('admin-clients-search');
    Route::get('clients-import', 'AdminClientController@clientImport')->name('clients.import');
    Route::post('clients-import', 'AdminClientController@clientImportSave')->name('clients.import');
    Route::post('client_payment', 'AdminClientController@clientPayment')->name('client-payment');
    Route::get('invoice_print/{id}', 'AdminClientController@invoicePrint')->name('invoice-print');
    Route::get('invoice_download/{id}', 'AdminClientController@invoicePdf')->name('invoice-download');
    Route::post('document_upload', 'AdminClientController@documentUpload')->name('document-upload');
    Route::resource('embassy-approve', 'AdminEmbassyApproveController');
    Route::post('embassy-approve-list', 'AdminEmbassyApproveController@embassyApproveList')->name('embassy-approve-list');
    Route::get('embassy-approve-import', 'AdminEmbassyApproveController@embassyApproveImport')->name('embassy-approve-import');
    Route::post('embassy-approve-import', 'AdminEmbassyApproveController@embassyApproveSave')->name('embassy-approve-import');
    Route::resource('medical-status', 'AdminMedicalStatus');
    Route::resource('malaysia-clients', 'MalaysiaClientController');
    Route::resource('hiaring-moods', 'AdminHiaringMoodController');
    Route::resource('companies', 'AdminCompanyController');
});

Route::middleware(['auth', 'editor', 'prevent-back-history'])->group(function () {
    Route::get('editor-dashboard', 'EditorDashboardController@index')->name('editor-dashboard');
    Route::resource('editor-clients', 'EditorClientController');
    Route::post('editor-clients-search', 'EditorClientController@editorClientsSearch')->name('editor-clients-search');
    Route::post('editor_client_payment', 'EditorClientController@clientPayment')->name('editor-client-payment');
    Route::get('editor_invoice_print/{id}', 'EditorClientController@invoicePrint')->name('editor-invoice-print');
    Route::get('editor_invoice_download/{id}', 'EditorClientController@invoicePdf')->name('editor-invoice-download');
    Route::post('editor_document_upload', 'EditorClientController@documentUpload')->name('editor-document-upload');
});

Route::middleware(['auth', 'viewer', 'prevent-back-history'])->group(function () {
    Route::get('viewer-dashboard', 'ViewerDashboardController@index')->name('viewer-dashboard');
});

Route::get('migrate/{key}', function ($key) {
    if ($key == 'Rejohn@1234') {
        try {
            \Artisan::call('migrate');
            echo 'Migrated Successfully!';
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    } else {
        echo 'Not matched!';
    }
});


Route::get('clear', function () {
    \Artisan::call('optimize:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    \Artisan::call('config:clear');
    echo "Run clear Successfully";
});

app/User.php
<?php

namespace App;

use App\Models\Company;
use App\Models\Role;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'role_id', 'company_id', 'first_name', 'last_name', 'email', 'phone', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $with = [
        'role', 'company'
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
use App\Models\Company;
use App\Models\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = User::with('role', 'company')->get();
        return view('admin.user.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        $companies = Company::all();
        return view('admin.user.create', compact('roles', 'companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        User::create([
            'role_id'       => $request->role_id,
            'company_id'    => $request->company_id,
            'first_name'    => $request->first_name,
            'last_name'     => $request->last_name,
            'email'         => $request->email,
            'phone'         => $request->phone,
            'password'      => Hash::make($request->password)
        ]);

        session()->flash('success', 'User Created Successfully.');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        $companies = Company::all();
        return view('admin.user.create', compact('user', 'roles', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {

        if ($request->filled('password') && $request->filled('password_confirmation')) {
            $rules['password']    = 'required|string|min:8|confirmed';
            $validator = Validator::make($request->all(), $rules);
            $validator->validate();

            $updateUser = $user->update([
                'role_id'       => $request->role_id,
                'company_id'    => $request->company_id,
                'first_name'    => $request->first_name,
                'last_name'     => $request->last_name,
                'email'         => $request->email,
                'phone'         => $request->phone,
                'password'      => Hash::make($request->password)
            ]);
        } else {
            $updateUser = $user->update([
                'role_id'       => $request->role_id,
                'company_id'    => $request->company_id,
                'first_name'    => $request->first_name,
                'last_name'     => $request->last_name,
                'email'         => $request->email,
                'phone'         => $request->phone,
            ]);
        }

        if ($updateUser) {
            session()->flash('success', 'User Updated Successfully.');
            return redirect()->route('users.index');
        } else {
            session()->flash('error', 'Something Happend Wrong');
            return redirect()->route('users.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.layout')

@if(isset($user))
@section('title', 'Create User')
@else
@section('title', 'Update User')
@endif

@section('content')

@component('partials.breadcrumb', [
'title' => isset($user) ? 'Update User' : 'Create User',
'activePage' => isset($user) ? 'Update User' : 'Create User'
])
@endcomponent

<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">@if(isset($user)) Update User Form @else Create User Form @endif</h3>
        </div>
        <form class="form-horizontal" action="{{ isset($user) ? route('users.update', $user->id) : route('users.store') }}" method="POST">
            @csrf
            @if(isset($user))
            @method('PUT')
            @endif
            <div class="box-body">
                <div class="form-group @error('first_name') has-error @enderror">
                    <label for="firstName" class="col-sm-2 control-label">User First Name <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="text" name="first_name" class="form-control" id="firstName" value="{{ isset($user) ? $user->first_name : old('first_name') }}" placeholder="Enter User First Name" required>
                        @error('first_name')
                        <span class="help-block text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('last_name') has-error @enderror">
                    <label for="lastName" class="col-sm-2 control-label">User Last Name <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="text" name="last_name" class="form-control" id="lastName" value="{{ isset($user) ? $user->last_name : old('last_name') }}" placeholder="Enter User Last Name" required>
                        @error('last_name')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('email') has-error @enderror">
                    <label for="userEmail" class="col-sm-2 control-label">User Email <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="userEmail" value="{{ isset($user) ? $user->email : old('email') }}" placeholder="Enter User Email" required>
                        @error('email')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('phone') has-error @enderror">
                    <label for="userMobile" class="col-sm-2 control-label">User Mobile Number <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="number" name="phone" class="form-control" id="userMobile" value="{{ isset($user) ? $user->phone : old('phone') }}" placeholder="Enter User Mobile Number (01XXXXXXXXX)" required>
                        @error('phone')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('company_id') has-error @enderror">
                    <label for="userCompany" class="col-sm-2 control-label">User Company <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <select class="form-control" id="userCompany" name="company_id" required>
                            <option value="0" @if(old('company_id') !=0) selected @endif>Select User Company</option>
                            @foreach ($companies as $company)
                            @if(isset($user))
                            <option @if(old('company_id', $user->company_id)==$company->id) selected @endif value="{{ $company->id }}">{{ $company->company_name }}</option>
                            @else
                            <option @if(old('company_id')==$company->id) selected @endif value="{{ $company->id }}">{{ $company->company_name }}</option>
                            @endif
                            @endforeach
                        </select>
                        @error('company_id')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('role_id') has-error @enderror">
                    <label for="userRole" class="col-sm-2 control-label">User Role <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <select class="form-control" id="userRole" name="role_id" required>
                            <option value="0" @if(old('role_id') !=0) selected @endif>Select User Role</option>
                            @foreach ($roles as $role)
                            @if(isset($user))
                            <option @if(old('role_id', $user->role_id)==$role->id) selected @endif value="{{ $role->id }}">{{ $role->name }}</option>
                            @else
                            <option @if(old('role_id')==$role->id) selected @endif value="{{ $role->id }}">{{ $role->name }}</option>
                            @endif
                            @endforeach
                        </select>
                        @error('role_id')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group @error('password') has-error @enderror">
                    <label for="userPassword" class="col-sm-2 control-label">User Password <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" id="userPassword" placeholder="Enter User Password" @if(isset($user)) @else required @endif>
                        @error('password')
                        <span class="help-block">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirmPassword" class="col-sm-2 control-label">Confirm Password <span class="text-danger">*</span></label>
                    <div class="col-sm-10">
                        <input type="password" name="password_confirmation" class="form-control" id="confirmPassword" placeholder="Confirm Password" @if(isset($user)) @else required @endif>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="{{ route('users.index') }}" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-info pull-right">@if(isset($user)) Update User @else Create User @endif</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.layout')

@section('title', 'Users List')

@section('content')

@component('partials.breadcrumb',[
'title' => 'User List',
'activePage' => 'User List'
])
@endcomponent

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">User List</h3>
                    <div class="box-tools">
                        <a href="{{ route('users.create') }}" type="button" class="btn btn-info btn-flat btn-xs pull-right">Add User</a>
                    </div>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>#</th>
                                <th>User Name</th>
                                <th>Company Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Create Date</th>
                                <th>User Type</th>
                                <th>Action</th>
                            </tr>
                            @forelse ($datas as $data)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $data->first_name }} {{ $data->last_name }}</td>
                                <td>@if(isset($data->company->company_name)){{ $data->company->company_name }}@endif</td>
                                <td>{{ $data->email }}</td>
                                <td>{{ $data->phone }}</td>
                                <td>{{ date('d-m-Y',strtotime($data->created_at)) }}</td>
                                <td><span class="label @if($data->role->slug === 'admin') label-success @elseif ($data->role->slug === 'editor') label-info @else label-warning @endif">{{ $data->role->name }}</span></td>
                                <td>
                                    {{-- <a href="#" type="button" class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Show {{ $data->first_name }} {{ $data->last_name }} Details"><i class="fa fa-eye"></i></a> --}}
                                    @if($data->editable)
                                    <a href="{{ route('users.edit', $data->id) }}" type="button" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Edit {{ $data->first_name }} {{ $data->last_name }} info"><i class="fa fa-edit"></i></a>
                                    @endif
                                    @if($data->deleteable)
                                    <a href="#" type="button" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete {{ $data->first_name }} {{ $data->last_name }}"><i class="fa fa-trash"></i></a>
                                    @endif
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">No User Created.</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('vendors/sweet-alert/sweetalert.css') }}">
@endsection

@section('scripts')
<script src="{{ asset('vendors/sweet-alert/sweetalert.js') }}"></script>
@if(session('success'))
<script>
    $(document).ready(function() {
        Swal.fire(
            'Good job!',
            "{{ session('success') }}",
            'success'
        );
    })
</script>
@endif

@if(session('error'))
<script>
    $(document).ready(function() {
        Swal.fire({
            title: "Alert",
            text: "{{ session('error') }}",
            icon: "error",
            showCancelButton: true,
            confirmButtonText: 'Exit',
            cancelButtonText: 'Stay on the page'
        });
    });
</script>
@endif
@endsection